<?php



header("Content-Type: application/json; charset=Windows-1252");

$str = '{"meta": {}, "objects": [{"has_long_appointment_new": false, "privacy_policy_validation_message": "We cannot complete your booking until you indicate that you have read and agree to the terms of our Privacy Policy. If you do not agree to these terms and wish to progress with your booking, please call our reception on (03) 9579 3522.", "enabled": true, "preferred_name": "", "has_extended_registration": false, "has_expired_medicare_card": false, "id": 1, "display_name": "Eastbound Family Practice", "has_medicare_demographic": false, "privacy_policy_confirmation_message": "I have read the Eastbound Family Practice Privacy Policy and agree to the handling of my personal information as outlined above and in the Eastbound Family Practice Privacy Policy.", "has_inclinic_checkin_demographics": false, "new_patient_default_appointment_type": null, "has_appointment_types": false, "checkin_mins_early": 120, "latitude": 0.0, "email": "", "practitioner_title": "Doctor", "notice": "", "privacy_policy": "<p>USE AND DISCLOSURE OF INFORMATION COLLECTED</p>\n\n<p>Eastbound Family Practice will not disclose information about your individual visits to our website or any of the personal\ninformation that you provide such as your name, address, telephone number, e-mail address or credit/debit card\ndetails to any outside parties without your consent except when required by law to do so.</p>\n\n<p>Eastbound Family Practice will only record your e-mail address if you send us a message. Your e-mail address will only be\nused or disclosed for the purpose for which you have provided it and it will not be added to a mailing list or\nused or disclosed for any other purpose without your consent unless you specifically request such action.</p>\n\n<p>Users are advised that there are inherent risks transmitting information across the internet.</p>\n\n<p>LINKS TO OTHER SITES</p>\n\n<p>Eastbound Family Practice may offer links to sites that are not operated or managed by Eastbound Family Practice. If you visit one of these\ninked sites, you should review their privacy and other policies. We are not responsible for the policies and\npractices of other companies.</p>\n\n<p>If you require further information, please contact Eastbound Family Practice on (03) 9579 3522.</p>", "has_address_demographic": false, "has_contact_demographic": false, "phone": "(03) 9579 3522", "has_inclinic_checkin": false, "address": "179 East Boundary Road, Bentleigh East 3165", "name": "Eastbound Family Practice", "suburb": "Bentleigh East VIC 3165", "url": "https://eastbound.healthsite.io/#appointments", "checkin_mins_late": 120, "send_sms": true, "longitude": 0.0, "has_nok_demographic": false, "appointment_type": [], "has_emergency_demographic": false, "order": 0, "has_long_appointment": false}]}';
//$str = mb_convert_encoding($str, "UTF-8","GBK");
echo $str;

?>